In [3]:
from scipy.ndimage import correlate
import numpy as np
input_img = np.arange(25).reshape(5, 5)
print(input_img)
weights = [[0, 1, 0],
		   [1, 2, 1],
		   [0, 1, 0]]
res_img = correlate(input_img, weights)
print(res_img)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  6  11  17  23  28]
 [ 31  36  42  48  53]
 [ 61  66  72  78  83]
 [ 91  96 102 108 113]
 [116 121 127 133 138]]


## Exercise 1


In [4]:
#Print the value in position (3, 3) in res_img. Explain the value?
print(res_img[3, 3])
#what happens here, the value is 108?
#The value is 108 because the value in position (3, 3) is calculated by the sum of the product of the input image and the weights.


108
